[font]
size = 14

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

